### PR TITLE
Travis to gitlab

### PR DESCRIPTION
**Pull request by burner**

### CODE REVIEW

**Comment by burner** [comment]
@kinke can you take a look at the one failing ldc windows test please

**Comment by kinke** [comment]
I'd move the `version(LDC)` before `version(Windows)` in https://github.com/symmetryinvestments/xlsxd/commit/96369ce8e8b762b70b06a62e2faf636eb92f6856.

**Comment by kinke** [comment]
The signature in druntime uses `FILE*`: https://github.com/ldc-developers/druntime/blob/ldc/src/core/stdc/stdio.d#L1321

So `version(LDC) import stdc.core.stdio : _IO_FILE = FILE;` hopefully does the job.

**Comment by burner** [comment]
v4.0.1 includes the changes

**Comment by kinke** [comment]
Perfect, thx!

**Pull request merged**
